# Generated by Django 5.0.6 on 2026-02-15 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория контента',
                'verbose_name_plural': 'Категории контента',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('language_code', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('AGE_PENDING', 'Ожидает подтверждения 18+'), ('ACTIVE', 'Активный'), ('BLOCKED_UNDERAGE', 'Заблокирован (младше 18)'), ('BLOCKED_ADMIN', 'Заблокирован администратором'), ('DELETED', 'Удален')], default='NEW', max_length=20, verbose_name='Статус')),
                ('is_18_confirmed', models.BooleanField(default=False, verbose_name='18+ подтверждено')),
                ('consent_accepted', models.BooleanField(default=False, verbose_name='Согласие принято')),
                ('consent_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия согласия')),
                ('consent_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время принятия согласия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(default='Тюмень', max_length=100, verbose_name='Город')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('level', models.CharField(default='Bronze', max_length=20, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='barsuk_app.contentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Позиция контента',
                'verbose_name_plural': 'Позиции контента',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('transfer', 'Трансфер'), ('manager', 'Менеджер')], max_length=20, verbose_name='Тип заявки')),
                ('data', models.JSONField(verbose_name='Данные заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('cancel', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('manager_notes', models.TextField(blank=True, null=True, verbose_name='Заметки менеджера')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='barsuk_app.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='barsuk_app__status_0fc927_idx'), models.Index(fields=['request_type'], name='barsuk_app__request_563943_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='Тип события')),
                ('event_data', models.JSONField(blank=True, null=True, verbose_name='Данные события')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время события')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='barsuk_app.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='barsuk_app__event_t_0f1242_idx'), models.Index(fields=['created_at'], name='barsuk_app__created_b354ae_idx')],
            },
        ),
    ]
